kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: darkweb-photo-indexer-pv-claim
spec:
  storageClassName: managed-nfs-storage
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 800Gi